version: '3.8'

services:
  nest_app:
    build: ./server
    container_name: nest_app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      UPLOAD_DIR: "/usr/src/app/dist/upload"
      JWT_SECRET: ${JWT_SECRET}
      BASE_URL: ${BASE_URL}
    volumes:
      - .:/usr/src/app
      - upload_data:/usr/src/app/dist/upload

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  next_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      BASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"

volumes:
  upload_data:
  postgres_data:
