enum Role {
  ADMIN = "ADMIN",
  RADIOLOGIST = "RADIOLOGIST",
}

enum Status {
  Created = "Created",
  Assigned = "Assigned",
  Reviewed = "Reviewed",
}

enum Specialization {
  NEURORADIOLOGY = "NEURORADIOLOGY",
  MUSCULOSKELETAL_RADIOLOGY = "MUSCULOSKELETAL_RADIOLOGY",
  ABDOMINAL_RADIOLOGY = "ABDOMINAL_RADIOLOGY",
  CARDIOVASCULAR_RADIOLOGY = "CARDIOVASCULAR_RADIOLOGY",
  BREAST_IMAGING = "BREAST_IMAGING",
  PEDIATRIC_RADIOLOGY = "PEDIATRIC_RADIOLOGY",
  THORACIC_RADIOLOGY = "THORACIC_RADIOLOGY",
  GENITOURINARY_RADIOLOGY = "GENITOURINARY_RADIOLOGY",
  INTERVENTIONAL_RADIOLOGY = "INTERVENTIONAL_RADIOLOGY",
  NUCLEAR_MEDICINE = "NUCLEAR_MEDICINE",
  EMERGENCY_RADIOLOGY = "EMERGENCY_RADIOLOGY",
  ONCOLOGIC_IMAGING = "ONCOLOGIC_IMAGING",
  GASTROINTESTINAL_RADIOLOGY = "GASTROINTESTINAL_RADIOLOGY",
  HEAD_AND_NECK_RADIOLOGY = "HEAD_AND_NECK_RADIOLOGY",
  ORTHOPEDIC_RADIOLOGY = "ORTHOPEDIC_RADIOLOGY",
  VASCULAR_AND_INTERVENTIONAL_RADIOLOGY = "VASCULAR_AND_INTERVENTIONAL_RADIOLOGY",
  ENDOVASCULAR_SURGICAL_NEURORADIOLOGY = "ENDOVASCULAR_SURGICAL_NEURORADIOLOGY",
  BODY_IMAGING = "BODY_IMAGING",
}

enum NotificationStatus {
  READ = "READ",
  UNREAD = "UNREAD",
}

enum NotificationType {
  GENERAL = "GENERAL",
  UNASSIGNED_REVIEW_REQUEST = "UNASSIGNED_REVIEW_REQUEST",
  REQUEST_ASSIGNED = "REQUEST_ASSIGNED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  REQUEST_REVIEWED = "REQUEST_REVIEWED",
  REQUEST_REPORT_RESUBMITTED = "REQUEST_REPORT_RESUBMITTED",
  REQUEST_REREVIEWED = "REQUEST_REREVIEWED",
  REVIEW_FEEDBACK_RECEIVED = "REVIEW_FEEDBACK_RECEIVED",
}

export { Role, Status, Specialization, NotificationStatus, NotificationType };
